[package]
name = "tutor"
version = "0.1.0"
authors = ["Abdun Nihaal <abdun.nihaal@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.1"
toml = "0.5.6"
serde = { version = "1.0", features = ["derive"] }
